Add link for merge app in top bar
gridsuite/commons-ui pull request #13
Opened 2020-08-27 15:13 UTC by med-hedi

2020-08-28 15:40 UTC, mikatheo commented
Could we see "GridStudy" and GridMerge" appear instead of "GridStudyApp" or "GridMergeApp", with the same style as the name of the application in the top right corner (so without the hypertext link).
![image](https://user-images.githubusercontent.com/18592604/91585956-0abef480-e955-11ea-82eb-44b3aad19e8f.png)

2020-09-01 08:18 UTC, geofjamg requested changes

2020-09-01 08:18 UTC, geofjamg commented on demo/src/app.js
> +                            studyAppColor={appConfig.studyAppColor}
Why do you pass this to the top bar component, we are not going to add a new property each time we have a new supported app?

2020-09-01 08:22 UTC, jonenst commented
I think the apps and their colors should be downloaded dynamically from some known place. This way we don't have to rerelease the commons-ui components and then rerelease all the apps when we add a new app or change a color. Also all the apps will update at the same time this way

2020-09-01 09:47 UTC, med-hedi commented
@geofjamg @jonenst if i understand correctly, i should not touch the common-ui but i have to define a color code in each grid merge and grid study application

2020-10-12 11:54 UTC, closed without merging