Add an error management when user validation is unavailable
gridsuite/commons-ui pull request #193
Opened 2022-11-02 11:21 UTC by sBouzols

Signed-off-by: sBouzols <sylvain.bouzols@gmail.com>

2022-11-02 14:45 UTC, jonenst approved these changes

2022-11-03 12:47 UTC, archendel requested changes
Works well except if user refresh pages when the new error message is displayed. In this case, an empty page appears

2022-11-04 16:16 UTC, sBouzols commented
> Works well except if user refreshes the page when the new error message is displayed. In this case, an empty page appears

Damn...

2022-11-08 09:34 UTC, archendel approved these changes
Test: OK
Code: OK

2022-11-08 10:59 UTC, merged