Migrate the RHF inputs from gridstudy-app to commons-ui
gridsuite/commons-ui pull request #277
Opened 2023-08-01 16:08 UTC by flomillot

2023-08-10 10:37 UTC, archendel requested changes

2023-08-10 10:37 UTC, archendel commented on demo/src/InputsTab.js
> +    [SWITCH_INPUT]: yup.boolean(),
```suggestion
    [AUTOCOMPLETE_INPUT]: yup.string().nullable(),
    [TEXT_INPUT]: yup.string(),
    [SLIDER_INPUT]: yup.number().nullable(),
    [SELECT_INPUT]: yup.string().nullable(),
    [RADIO_INPUT]: yup.string().nullable(),
    [INTEGER_INPUT]: yup.number().nullable(),
    [FLOAT_INPUT]: yup.number().nullable(),
    [CHECKBOX_INPUT]: yup.boolean(),
    [SWITCH_INPUT]: yup.boolean(),
```

2023-08-10 10:37 UTC, archendel commented on demo/src/InputsTab.js
> +    [SWITCH_INPUT]: null,
```suggestion
    [AUTOCOMPLETE_INPUT]: null,
    [TEXT_INPUT]: '',
    [SLIDER_INPUT]: null,
    [SELECT_INPUT]: null,
    [RADIO_INPUT]: null,
    [INTEGER_INPUT]: null,
    [FLOAT_INPUT]: null,
    [CHECKBOX_INPUT]: false, // or null, but should then be nullable in schema
    [SWITCH_INPUT]: false, // or null, but should then be nullable in schema
```

2023-08-10 10:37 UTC, archendel commented on src/components/react-hook-form/utils/constants.js
does not seem to be used anywhere

2023-08-10 13:01 UTC, flomillot commented on src/components/react-hook-form/utils/constants.js
You're right, thanks

2023-08-10 13:06 UTC, flomillot commented on README.md
It's on purpose, I just fixed the quotes

2023-08-14 12:25 UTC, archendel approved these changes

2023-08-16 14:49 UTC, thangqp commented on demo/src/InputsTab.js
> +import React from 'react';
Missing Copy right text

2023-08-16 16:52 UTC, thangqp approved these changes
OK

2023-08-17 08:51 UTC, merged