Vite migration minimal
gridsuite/commons-ui pull request #352
Opened 2024-02-16 15:15 UTC by flomillot

2024-02-16 16:55 UTC, jonenst approved these changes

2024-02-16 21:06 UTC, Tristan-WorkGH requested changes

2024-02-16 21:08 UTC, Tristan-WorkGH commented
Also from <https://vitejs.dev/guide/features#typescript>, it seem that vite won't do a check with `tsc` like CRA.  
Would need to include typescript checks in eslint or babel-eslint pipeline, vite plugin don't seem good.

2024-02-16 21:53 UTC, Tristan-WorkGH requested changes

2024-02-16 21:53 UTC, Tristan-WorkGH commented on vite.config.mts
> +    build: {
Have found how to keep file files compiled separately in bundle:
```suggestion
    build: {
        rollupOptions: {
            output: {
                preserveModules: true,
                entryFileNames: '[name].js',
            },
        },
```

Result: 
![image](https://github.com/gridsuite/commons-ui/assets/135599584/229026ff-30cc-4ab2-b1b6-a12cabde607d)

2024-02-19 11:53 UTC, flomillot commented on vite.config.mts
> +import { defineConfig } from 'vite';
Done

2024-02-19 11:53 UTC, flomillot commented on package.json
> +        "lint": "eslint . --ext js,jsx,ts,tsx"
Added prepublish, eslint in an other PR

2024-02-19 11:54 UTC, flomillot commented on vite.config.mts
> +            entry: resolve(__dirname, 'src/index.js'),
Done

2024-02-19 11:54 UTC, flomillot commented on vite.config.mts
> +import { resolve } from 'path';
Done

2024-02-19 11:55 UTC, flomillot commented on vite.config.mts
> +import * as url from 'url';
Done

2024-02-19 12:02 UTC, Tristan-WorkGH commented on vite.config.mts
> +function reactVirtualized(): PluginOption {
not mandatory

2024-02-19 12:09 UTC, flomillot commented on vite.config.mts
> +        dts(),
Will do an other PR and remove dts plugin

2024-02-19 12:09 UTC, flomillot commented on vite.config.mts
> +            formats: ['es'],
Nope

2024-02-19 12:09 UTC, flomillot commented on tsconfig.json
> +}
Done

2024-02-19 12:19 UTC, flomillot commented on package.json
> +    "module": "./dist/commons-ui.js",
We keep previous behaviour where only imports from root are allowed

2024-02-19 12:20 UTC, flomillot commented on package.json
> +    "module": "./dist/commons-ui.js",
Will do an other PR

2024-02-20 10:36 UTC, Tristan-WorkGH requested changes

2024-02-20 10:36 UTC, Tristan-WorkGH commented on vite.config.mts
> +import * as path from 'path';
```suggestion
import * as path from 'node:path';
```

2024-02-20 10:36 UTC, Tristan-WorkGH commented on .babelrc.json
> +}
missing new line
```suggestion
}

```

2024-02-20 10:42 UTC, flomillot commented on vite.config.mts
> +import * as path from 'path';
Done

2024-02-20 10:42 UTC, flomillot commented on .babelrc.json
> +}
DOne

2024-02-20 11:02 UTC, merged

2024-02-20 17:53 UTC, flomillot commented on package.json
>      "eslintConfig": {
I don't see it in the readme, where is it ?