Remove React imports
gridsuite/commons-ui pull request #356
Opened 2024-02-23 00:15 UTC by Tristan-WorkGH

Since React 17, it's [no longer necessary to `import React from 'react'`](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html).

[_goodbye-react-imports-17_](https://www.linkedin.com/pulse/say-goodbye-react-imports-17s-game-changing-feature-deepak-sharma-)

2024-02-23 13:37 UTC, flomillot approved these changes

2024-03-18 09:29 UTC, sBouzols commented on src/components/ElementSearchDialog/element-search-dialog.jsx
> +                                    <Fragment>
<></> instead of Fragment ?

2024-03-18 09:35 UTC, sBouzols requested changes
Prefer `<></>` usage instead of importing `Fragment`

2024-03-21 08:23 UTC, sBouzols approved these changes

2024-03-21 08:47 UTC, Tristan-WorkGH commented
strange, the CI have run, but the status isn't reported here...  
[Tristan-WorkGH/rte-gridsuite-commons-ui/actions](https://github.com/Tristan-WorkGH/rte-gridsuite-commons-ui/actions/workflows/build.yml)

2024-03-21 09:29 UTC, Tristan-WorkGH commented
Asked for help on https://github.com/orgs/community/discussions/113526

2024-03-21 09:32 UTC, merged