Clean declaration file
gridsuite/commons-ui pull request #357
Opened 2024-02-23 10:06 UTC by flomillot

2024-02-23 14:46 UTC, Tristan-WorkGH requested changes
good for me after that

2024-02-23 14:46 UTC, Tristan-WorkGH commented on src/index.d.ts
> +}
missing new line
```suggestion
}

```

2024-02-23 15:46 UTC, flomillot commented on src/index.d.ts
> +}
Ah yes, fixing eslint rn, thanks

2024-02-26 23:33 UTC, Tristan-WorkGH approved these changes

2024-02-28 09:40 UTC, merged