CustomMuiDialog can have a confirmation dialog
gridsuite/commons-ui pull request #548
Opened 2024-08-06 12:34 UTC by dbraquart

2024-08-07 16:26 UTC, ayolab approved these changes

2024-08-09 08:01 UTC, Tristan-WorkGH requested changes

2024-08-09 08:01 UTC, Tristan-WorkGH commented on src/components/dialogs/custom-mui-dialog.tsx
> +            />
maybe enclose it in a condition to not have null case for the msg key

```suggestion
    {confirmationMessage && (
            <PopupConfirmationDialog
                message={confirmationMessage}
                openConfirmationPopup={openConfirmationPopup}
                setOpenConfirmationPopup={setOpenConfirmationPopup}
                handlePopupConfirmation={handlePopupConfirmation}
            />)}
```

2024-08-14 07:50 UTC, Tristan-WorkGH requested changes

2024-08-14 07:50 UTC, Tristan-WorkGH commented on src/hooks/useConfidentialityWarning.ts
> +    const [confidentialityWarningKey, setConfidentialityWarningKey] = useState<string>();
```suggestion
    const [confidentialityWarningKey, setConfidentialityWarningKey] = useState<string>('');
```

2024-08-14 10:27 UTC, Tristan-WorkGH approved these changes

2024-08-14 10:39 UTC, merged