remove tooltip text in expert filter components
gridsuite/commons-ui pull request #603
Opened 2024-10-08 15:25 UTC by basseche

2024-10-10 15:09 UTC, Mathieu-Deharbe requested changes
There is one left : 

![tooltips](https://github.com/user-attachments/assets/a5ac2392-6aa1-4d0c-90bc-b1aed3256ce1)

I think the second one "Rule group at path 2" should be removed as well. It is part of the react query builder auto tooltip system. But see with the PO.

Plus (if you feel like it) "Drag handle" but I am not sure at all about it.

2024-10-14 11:33 UTC, basseche commented
> There is one left :
> 
> ![tooltips](https://private-user-images.githubusercontent.com/148252167/375436591-a5ac2392-6aa1-4d0c-90bc-b1aed3256ce1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDU4NTQsIm5iZiI6MTcyODkwNTU1NCwicGF0aCI6Ii8xNDgyNTIxNjcvMzc1NDM2NTkxLWE1YWMyMzkyLTZhYTEtNGQwYy05MGJjLWIxYWVkMzI1NmNlMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxMTMyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWU2NjIzMTJlODk4ZmI0ZWJlMzZlNjZhNGZkNDFjY2U1MGZiNWU2MmNkY2NlMmZiM2E4NWY0NmY4NzA5OWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.d8O_E3g74hIcQ6Db9HLA700-Loo75ekmJ1Snf8mUJNE) [ ![tooltips](https://private-user-images.githubusercontent.com/148252167/375436591-a5ac2392-6aa1-4d0c-90bc-b1aed3256ce1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDU4NTQsIm5iZiI6MTcyODkwNTU1NCwicGF0aCI6Ii8xNDgyNTIxNjcvMzc1NDM2NTkxLWE1YWMyMzkyLTZhYTEtNGQwYy05MGJjLWIxYWVkMzI1NmNlMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxMTMyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWU2NjIzMTJlODk4ZmI0ZWJlMzZlNjZhNGZkNDFjY2U1MGZiNWU2MmNkY2NlMmZiM2E4NWY0NmY4NzA5OWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.d8O_E3g74hIcQ6Db9HLA700-Loo75ekmJ1Snf8mUJNE) ](https://private-user-images.githubusercontent.com/148252167/375436591-a5ac2392-6aa1-4d0c-90bc-b1aed3256ce1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDU4NTQsIm5iZiI6MTcyODkwNTU1NCwicGF0aCI6Ii8xNDgyNTIxNjcvMzc1NDM2NTkxLWE1YWMyMzkyLTZhYTEtNGQwYy05MGJjLWIxYWVkMzI1NmNlMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxMTMyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWU2NjIzMTJlODk4ZmI0ZWJlMzZlNjZhNGZkNDFjY2U1MGZiNWU2MmNkY2NlMmZiM2E4NWY0NmY4NzA5OWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.d8O_E3g74hIcQ6Db9HLA700-Loo75ekmJ1Snf8mUJNE) [ ](https://private-user-images.githubusercontent.com/148252167/375436591-a5ac2392-6aa1-4d0c-90bc-b1aed3256ce1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDU4NTQsIm5iZiI6MTcyODkwNTU1NCwicGF0aCI6Ii8xNDgyNTIxNjcvMzc1NDM2NTkxLWE1YWMyMzkyLTZhYTEtNGQwYy05MGJjLWIxYWVkMzI1NmNlMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxMTMyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWU2NjIzMTJlODk4ZmI0ZWJlMzZlNjZhNGZkNDFjY2U1MGZiNWU2MmNkY2NlMmZiM2E4NWY0NmY4NzA5OWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.d8O_E3g74hIcQ6Db9HLA700-Loo75ekmJ1Snf8mUJNE)
> 
> I think the second one "Rule group at path 2" should be removed as well. It is part of the react query builder auto tooltip system. But see with the PO.
> 
> Plus (if you feel like it) "Drag handle" but I am not sure at all about it.

@Mathieu-Deharbe : all resolved in new commit

2024-10-15 09:26 UTC, Mathieu-Deharbe approved these changes
Found a last kind of useless tooltip. Not asked in the initial ticket but do as you wish : 

![open tooltip](https://github.com/user-attachments/assets/e7ece3ec-f829-47c4-94e3-2b73cd15a342)

Approved anyway.

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/CustomReactQueryBuilder.tsx
> +
We can use useMemo to override the whole defaultTranslations with empty title for components.
In the future, if we need translation, only replace empties by useInlt

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/CombinatorSelector.tsx
> +                title="" // disable the tooltip
To remove

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/CustomReactQueryBuilder.tsx
> +    return <AddButton {...props} label="rule" title="" />;
```suggestion
    return <AddButton {...props} label="rule" />;
```

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/CustomReactQueryBuilder.tsx
> +    return <AddButton {...props} label="subGroup" title="" />;
```suggestion
    return <AddButton {...props} label="subGroup" />;
```

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/FieldSelector.tsx
> +            title=""
```suggestion
            title={title}
```

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/RemoveButton.tsx
> +        <IconButton size="small" onClick={() => handleDelete()} className={className} title="">
```suggestion
        <IconButton size="small" onClick={() => handleDelete()} className={className} title={title}>
```

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/TextValueEditor.tsx
> +        return <MaterialValueEditor {...props} title={title} />;
```suggestion
        return <MaterialValueEditor {...props} />;
```

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/TranslatedValueEditor.tsx
> +        return <MaterialValueEditor {...props} values={translatedValues} title={title} />;
```suggestion
        return <MaterialValueEditor {...props} values={translatedValues} />;
```

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/ValueEditor.tsx
> +        return <CountryValueEditor {...props} title="" />;
```suggestion
        return <CountryValueEditor {...props} />;
```

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/ValueEditor.tsx
> +        return <TranslatedValueEditor {...props} title="" />;
```suggestion
        return <TranslatedValueEditor {...props} />;
```

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/ValueEditor.tsx
> +        return <TextValueEditor {...props} title="" />;
```suggestion
        return <TextValueEditor {...props} />;
```

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/PropertyValueEditor.tsx
> +    title: string;
To remove

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/PropertyValueEditor.tsx
> +                    title={title}
```suggestion
                    title={valueEditorProp?.title}
```

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/PropertyValueEditor.tsx
> +                    title={title}
```suggestion
                    title={valueEditorProp?.title}
```

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/PropertyValueEditor.tsx
> +                    title={title}
```suggestion
                    title={valueEditorProp?.title}
```

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/ValueEditor.tsx
> +        return <PropertyValueEditor equipmentType={equipmentType} valueEditorProps={props} title="" />;
```suggestion
        return <PropertyValueEditor equipmentType={equipmentType} valueEditorProps={props} />;
```

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/ValueEditor.tsx
> +        return <GroupValueEditor {...props} title="" />;
```suggestion
        return <GroupValueEditor {...props} />;
```

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/ValueEditor.tsx
> +                title="" // disable the tooltip
To remove

2024-10-15 14:53 UTC, thangqp commented on src/components/inputs/reactQueryBuilder/ValueSelector.tsx
> +            title="" // disable the tooltip
To remove

2024-10-16 07:19 UTC, basseche commented on src/components/inputs/reactQueryBuilder/CustomReactQueryBuilder.tsx
> +    return <AddButton {...props} label="subGroup" title="" />;
ok thanks

2024-10-16 08:08 UTC, basseche commented on src/components/inputs/reactQueryBuilder/CombinatorSelector.tsx
> +                title="" // disable the tooltip
ok

2024-10-16 08:09 UTC, basseche commented on src/components/inputs/reactQueryBuilder/CustomReactQueryBuilder.tsx
> +    return <AddButton {...props} label="rule" title="" />;
ok

2024-10-16 08:10 UTC, basseche commented on src/components/inputs/reactQueryBuilder/FieldSelector.tsx
> +            title=""
ok

2024-10-16 08:16 UTC, basseche commented on src/components/inputs/reactQueryBuilder/TranslatedValueEditor.tsx
> +        return <MaterialValueEditor {...props} values={translatedValues} title={title} />;
ok

2024-10-16 12:51 UTC, Mathieu-Deharbe approved these changes

2024-10-16 12:51 UTC, Mathieu-Deharbe commented on src/components/inputs/reactQueryBuilder/CustomReactQueryBuilder.tsx
> +};
Nice ! Ok @thangqp you are and remain the React query builder master.

2024-10-16 15:16 UTC, thangqp approved these changes
Test OK

2024-10-16 15:24 UTC, merged